# Generated by Django 4.1.1 on 2022-09-15 10:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_post_image_postview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='smileicon.jpg', upload_to=blog.models.user_directory_path),
        ),
    ]
